### ISSUE TITLE
Failed to pull singularity image

### ISSUE THREAD

**Issue by Galaxy-228** [i2bc/dense#2]
Hi,
When I tried to test the DENSE software using the official tutorial with the command nextflow run i2bc/dense -profile singularity,test, the following error occurred.
![image](https://github.com/user-attachments/assets/e85f5b31-3a54-4934-b63a-94c46fde9472)

This seems to be caused by the inability to access the Docker website. This seems to be an unsolvable problem for me.

I have already obtained the taxonomically restricted genes (TRGs) and the evolutionary relationship between the genomes (tree file).  In this situation, if I want to identify de novo genes, do you have any suggestions or methods when it's not possible to use Nextflow?

Best,
Jie

**Comment by Proginski** [comment]
Dear Jie,

You used  the command
`nextflow run i2bc/dense -profile singularity,test`

The error message you're encountering suggests that Nextflow is having trouble pulling the Singularity image from the Docker registry. This could be due to a network issue, as indicated by the "i/o timeout" message.

Unfortunately, you need to access the Docker registry to execute DENSE. However, you could explore the possibility that this issue is related to the size of the image (615.62MB) and/or to the speed/stability of your internet connection.

**Here are a few potential solutions**:

**Check your internet connection** (and its stability).

**Increase the pull timeout**: You could try increasing the singularity.pullTimeout in the Nextflow configuration. This can be done by adding the following line to your nextflow.config file:
`singularity {
    pullTimeout = '60m'
}`

**Pull the image manually**: If the above steps don't work, you could try pulling the image manually using Singularity:
`singularity pull /path/to/DENSE/containers/lopesi2bc-denovogenes.img docker://lopesi2bc/denovogenes`
... or you could start with this one if you want to save time !

I hope this helps! Let me know if you have any other questions.

Best, Paul

**Comment by Galaxy-228** [comment]
Dear Paul,
Thanks so much for your reply,
It's due to network issues. I have already manually downloaded the Docker image from the WeTransfer link that you gave: [https://wetransfer.com/downloads/6c52eae25ab50c63d60d6ffe4b6ac91620241011085605/70e80e2672820d385fea2daf1ee49c2520241011085618/e98f74](https://wetransfer.com/downloads/6c52eae25ab50c63d60d6ffe4b6ac91620241011085605/70e80e2672820d385fea2daf1ee49c2520241011085618/e98f74?trk=TRN_TDL_01&utm_campaign=TRN_TDL_01&utm_medium=email&utm_source=sendgrid).

I hope this will be helpful for others who encounter the same problem.
Best,
Jie
